pipeline {
    agent any

    tools {
        maven 'maven'
    }
    environment {
        env = "demo"
        app_name = "demo-mudi"
        tag = "${emv}_${BUILD_ID}"
        region = "us-west-1"
        ecr_repo = "219252656223.dkr.ecr.us-west-1.amazonaws.com"
        cluster = "demo-mudi"
    }
    stages {
        stage('Build') {
            steps {
                sh (
                    script: '''
                    cd demo-app
                    mvn clean install
                    aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${ecr_repo}
                    docker build -t ${ecr_repo}/${app_name}:${tag} .
                    docker push ${ecr_repo}/${app_name}:${tag}
                    ''',
                    returnStdout: true
                    )
            }
        }
        stage('Deploy') {
            steps{
                sh (
                    script: '''
                    TASK_DEF=$(aws ecs register-task-definition --region ${region} --family ${app_name} --container-definitions '[{"name": "app","image": "${ecr_repo}/${app_name}:${tag}"}]' --query 'taskDefinition.revision')
                    aws ecs update-service --cluster ${cluster} --region ${region} --service ${app_name} --task-definition ${app_name}:$TASK_DEF
                    echo "deployed!"
                    ''',
                    returnStdout: true
                )
            }
        }

    }
        post {
            always {
                cleanWs deleteDirs: true, notFailBuild: true
            }
        }
}
